version: "3"
services:
  postgres:
    container_name: stream_db
    image: postgres:14.3-alpine
    restart: always
    env_file: .env
    ports: 
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    container_name: stream_redis
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"
  stream_server1:
    container_name: stream_server1
    env_file: ./configs/docker.env
    build:
      context: .
    depends_on:
      - postgres
      - redis
    ports:
      - "50051:50051"
      - "8080:8080"
  stream_server2:
    container_name: stream_server2
    env_file: ./configs/docker.env
    build:
      context: .
    depends_on:
      - postgres
      - redis
    ports:
      - "50052:50051"
      - "8081:8080"
  stream_server3:
    container_name: stream_server3
    env_file: ./configs/docker.env
    build:
      context: .
    depends_on:
      - postgres
      - redis
    ports:
      - "50053:50051"
      - "8082:8080"
  stream_client1:
    container_name: stream_client
    build:
      context: .
    depends_on:
      - stream_server1
      - stream_server2
      - stream_server3
    command: ["client", "watch", "-c", "./configs/gostream.toml"]

volumes:
  db:
