[server]
dry_run = false
grpc_port = 50051
http_port = 8080
log_file = ''
# dsn = ... # better set from .env file (see env.example)
# redis_url = ... # better set from .env file (see env.example)
run_migrations = true
